fix issues with spdlog
ZhenshengLee/perception_cupoch pull request #15
Opened 2021-10-20 10:29 UTC by jediofgever

Hi, 
the foxy branch won't build without linking `spdlog`, 

```
1 error detected in the compilation of "/home/atas/colcon_ws/src/perception_cupoch/cupoch_conversions/src/cupoch_conversions.cu".
CMake Error at cupoch_conversions_generated_cupoch_conversions.cu.o.Release.cmake:280 (message):
  Error generating file
  /home/atas/colcon_ws/build/cupoch_conversions/CMakeFiles/cupoch_conversions.dir/src/./cupoch_conversions_generated_cupoch_conversions.cu.o
```

The PR has included linking of `spdlog`

A few humble opinions that might be helpful and improve `cupoch` and its ROS integration;

* `colcon` of ROS2 is actually able to build cupoch inside a workspace(e.g `colcon_ws`), this may not be desirable for some, as cupoch is a large library and takes time to build, but some may find it useful if they are actively modifying/developing code within cupoch, so you don't need to separately build ROS2 packages and cupoch.  

* I have copied the cmake files in `perception_cupoch` and used them to build ROS2 package, 
THank you ! these are very valuable, is there anything to do to simplify these files ? It took me some time to get my head around and build  MWE with `cupoch`, `perception_cupoch` and my own ROS2 code

2021-10-25 02:29 UTC, ZhenshengLee commented
@jediofgever thank you for your report and contributions!

> * `colcon` of ROS2 is actually able to build cupoch inside a workspace(e.g `colcon_ws`)

Yes you are right

> * as cupoch is a large library and takes time to build,  but some may find it useful if they are actively modifying/developing code within cupoch

You can do some separation of interests, and just add a package named `cupoch_contrib`(I already have it https://github.com/ZhenshengLee/cupoch_contrib , let's do it together), like opencv and [opencv_contrib](https://github.com/opencv/opencv_contrib), apollo, [apollo_contrib](https://github.com/ApolloAuto/apollo-contrib)

> is there anything to do to simplify these files ?

Yes you can! In CMake it's a common case to write a `FindCupoch.cmake` file to help developer get better cpp intergrations.
Check this issue if you like  https://github.com/ZhenshengLee/perception_cupoch/issues/3
After this, you can use cupoch only through `find_package(cupoch)` as easy as OpenCV.

2021-10-25 02:36 UTC, ZhenshengLee requested changes
${spdlog_LIBRARIES} and spdlog are repeated, choose one and delete the other.

2021-10-25 02:36 UTC, ZhenshengLee commented on cupoch_conversions/cmake/ga_build_common.cmake
>      spdlog
`${spdlog_LIBRARIES}` and `spdlog` are repeated, choose one and delete the other.

2021-12-16 01:20 UTC, ZhenshengLee requested changes
Will have to change. Thanks.

2021-12-16 01:20 UTC, ZhenshengLee commented on cupoch_conversions/CMakeLists.txt
> +APPEND_TARGET_ARCH_FLAGS()
repeated and trivial changes.

2021-12-16 01:20 UTC, ZhenshengLee commented on cupoch_conversions/CMakeLists.txt
> +include(GATest)
add this into `cupoch_conversions/cmake/ga_build_common.cmake`  line 107 rather than here.

2021-12-16 01:20 UTC, ZhenshengLee commented on cupoch_conversions/cmake/ga_build_common.cmake
> +set(CUPOCH_ROOT $ENV{HOME}/colcon_ws/install/cupoch)
Do not commit this change. Individual developer maintains his/her own paths.

2022-04-05 02:20 UTC, ZhenshengLee commented
@jediofgever  friendly ping for any update?

2022-04-06 15:22 UTC, closed without merging

2022-04-06 20:16 UTC, jediofgever commented
@ZhenshengLee apologies, I forget to keep track of this, I was planning to take a look into it one of these days